"""Report generation: save reports to DATA/reports/."""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path

from litgraph.settings import get_settings

logger = logging.getLogger(__name__)


def save_report(
    content: str,
    report_type: str,
    data_dir: Path | None = None,
) -> Path:
    """Save a report to DATA/reports/{timestamp}_{type}.md.

    Args:
        content: Report content as Markdown.
        report_type: Report type identifier (e.g., "innovation").
        data_dir: DATA directory path.

    Returns:
        Path to the saved report file.
    """
    if data_dir is None:
        data_dir = get_settings().data_dir

    reports_dir = data_dir / "reports"
    reports_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    filename = f"{timestamp}_{report_type}.md"
    path = reports_dir / filename

    settings = get_settings()
    header = (
        f"<!-- Generated by LitGraph | mode: {settings.mode} | "
        f"model: {settings.llm.best_model} | "
        f"timestamp: {timestamp} -->\n\n"
    )

    path.write_text(header + content, encoding="utf-8")
    logger.info("Report saved: %s", path)
    return path
