"""Tests for innovation analysis and report generation."""

from __future__ import annotations

import os
from pathlib import Path
from unittest.mock import patch

import pytest

from litgraph.settings import reset_settings


@pytest.fixture(autouse=True)
def _clean(monkeypatch):
    reset_settings()
    monkeypatch.setenv("LITGRAPH_MODE", "pro")
    yield
    reset_settings()


@pytest.fixture
def project_root(tmp_path):
    """Create minimal config for settings."""
    config_dir = tmp_path / "config"
    config_dir.mkdir()
    prompts_dir = config_dir / "prompts"
    prompts_dir.mkdir()

    (config_dir / "questions.yaml").write_text(
        "version: 1\nquestions:\n  - id: test\n    text: Test?\n"
    )
    (config_dir / "schema.yaml").write_text("node_types: {}\n")
    (config_dir / "config.default.yaml").write_text("{}\n")
    (prompts_dir / "innovation.yaml").write_text(
        "version: 1\n"
        "system: You are an innovation analyst.\n"
        "template: |\n"
        "  KG: {{ kg_context }}\n"
        "  Papers: {{ papers_summary }}\n"
        "  Scope: {{ scope }}\n"
    )
    return tmp_path


class TestIdentifyInnovations:
    @patch("litgraph.analysis.innovation.complete")
    def test_basic_innovation(self, mock_complete, data_dir, project_root):
        mock_complete.return_value = "## Research Gaps\n\n1. Gap A\n2. Gap B\n"

        from litgraph.settings import get_settings
        get_settings(project_root=project_root, force_reload=True)

        from litgraph.analysis.innovation import identify_innovations
        result = identify_innovations(scope="all", data_dir=data_dir)
        assert "Research Gaps" in result
        mock_complete.assert_called_once()

    @patch("litgraph.analysis.innovation.complete")
    def test_includes_kg_context(self, mock_complete, data_dir, project_root):
        mock_complete.return_value = "Report content"

        from litgraph.settings import get_settings
        get_settings(project_root=project_root, force_reload=True)

        from litgraph.analysis.innovation import identify_innovations
        identify_innovations(scope="all", data_dir=data_dir)

        # Check the prompt included KG context
        call_args = mock_complete.call_args
        prompt = call_args[0][0]
        assert "KG:" in prompt

    @patch("litgraph.analysis.innovation.complete")
    def test_includes_papers_summary(self, mock_complete, data_dir, project_root):
        mock_complete.return_value = "Report content"

        from litgraph.settings import get_settings
        get_settings(project_root=project_root, force_reload=True)

        # Create a fake analysis file
        analysis_dir = data_dir / "analysis"
        analysis_dir.mkdir(exist_ok=True)
        (analysis_dir / "test_paper.md").write_text("# Test Paper\n\nAnalysis content.")

        from litgraph.analysis.innovation import identify_innovations
        identify_innovations(scope="all", data_dir=data_dir)

        call_args = mock_complete.call_args
        prompt = call_args[0][0]
        assert "test_paper" in prompt

    @patch("litgraph.analysis.innovation.complete")
    def test_empty_kg_still_works(self, mock_complete, data_dir, project_root):
        """Innovation analysis should work even with empty KG."""
        mock_complete.return_value = "## Innovation Report\n\nSome findings."

        from litgraph.settings import get_settings
        get_settings(project_root=project_root, force_reload=True)

        from litgraph.analysis.innovation import identify_innovations
        result = identify_innovations(scope="all", data_dir=data_dir)
        assert isinstance(result, str)
        assert len(result) > 0


class TestSaveReport:
    def test_creates_report_file(self, data_dir, project_root, monkeypatch):
        from litgraph.settings import get_settings
        get_settings(project_root=project_root, force_reload=True)

        from litgraph.output.report import save_report
        path = save_report("# Test Report\n\nContent here.", "innovation", data_dir)
        assert path.exists()
        assert "innovation" in path.name
        assert path.suffix == ".md"

    def test_report_has_metadata_comment(self, data_dir, project_root, monkeypatch):
        from litgraph.settings import get_settings
        get_settings(project_root=project_root, force_reload=True)

        from litgraph.output.report import save_report
        path = save_report("Content", "test", data_dir)
        content = path.read_text()
        assert "<!-- Generated by LitGraph" in content
        assert "mode:" in content

    def test_report_in_correct_dir(self, data_dir, project_root, monkeypatch):
        from litgraph.settings import get_settings
        get_settings(project_root=project_root, force_reload=True)

        from litgraph.output.report import save_report
        path = save_report("Content", "innovation", data_dir)
        assert path.parent == data_dir / "reports"
